name: Telegram Bot

on:
  workflow_dispatch:
  push:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Code herunterladen
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Abhängigkeiten installieren
        run: pip install -r requirements.txt

      - name: Bot starten
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
